import type { TConfig } from "@/app/modules/config";
import { LogClass, maskEmail } from "@/app/modules/logger";
import { Inject, Injectable, Logger } from "@nestjs/common";
import { ConfigService } from "@nestjs/config";

const _RESEND_EMAILS_URL = "https://api.resend.com/emails";
const _REQUEST_TIMEOUT_MS = 10_000;

/**
 * Sends transactional email through the Resend HTTP API over plain `fetch`.
 *
 * With no `RESEND_API_KEY` (development only -- config requires it in
 * production) the link is logged instead of sent, so sign-in works locally.
 */
@LogClass()
@Injectable()
export class ResendAdapter {
	private readonly _logger = new Logger(ResendAdapter.name);
	private readonly _apiKey: string | undefined;
	private readonly _from: string;

	constructor(
		@Inject(ConfigService)
		private readonly _configService: ConfigService<TConfig>,
	) {
		this._apiKey = this._configService.get("RESEND_API_KEY");
		this._from = this._configService.getOrThrow("RESEND_FROM_EMAIL");
	}

	/** Whether real delivery is configured. */
	public isConfigured(): boolean {
		return Boolean(this._apiKey);
	}

	/** Emails the sign-in link; throws on a non-2xx Resend response. */
	public async sendMagicLink(
		toAddress: string,
		magicLinkUrl: string,
		expiresInMinutes: number,
	): Promise<void> {
		if (!this._apiKey) {
			this._logDevLink(toAddress, magicLinkUrl);
			return;
		}
		const response = await fetch(_RESEND_EMAILS_URL, {
			method: "POST",
			headers: {
				Authorization: `Bearer ${this._apiKey}`,
				"Content-Type": "application/json",
			},
			body: JSON.stringify({
				from: this._from,
				to: [toAddress],
				subject: "Your Nearplate sign-in link",
				html: this._html(magicLinkUrl, expiresInMinutes),
				text: this._text(magicLinkUrl, expiresInMinutes),
			}),
			signal: AbortSignal.timeout(_REQUEST_TIMEOUT_MS),
		});
		if (!response.ok) {
			throw new Error(`Resend responded with ${response.status}`);
		}
	}

	/**
	 * Development fallback: prints the link so sign-in works without email. The
	 * URL goes in its own field because the logger redacts `token=` inside
	 * message strings. Refuses to run in production, where a logged link would
	 * be a leaked credential (config already requires the key there).
	 */
	private _logDevLink(toAddress: string, magicLinkUrl: string): void {
		if (this._configService.get("NODE_ENV") === "production") {
			throw new Error("RESEND_API_KEY is required in production");
		}
		this._logger.warn({
			message: `RESEND_API_KEY not set; magic link for ${maskEmail(toAddress)}`,
			magicLinkUrl,
		});
	}

	/** HTML body; the URL is generated by us, never user input. */
	private _html(url: string, minutes: number): string {
		return `<p>Click to sign in to Nearplate:</p><p><a href="${url}">Sign in</a></p><p>This link expires in ${minutes} minutes and can be used once. If you didn't ask for it, ignore this email.</p>`;
	}

	/** Plain-text alternative. */
	private _text(url: string, minutes: number): string {
		return `Sign in to Nearplate: ${url}\n\nThis link expires in ${minutes} minutes and can be used once. If you didn't ask for it, ignore this email.`;
	}
}
