import type { TConfig } from "@/app/modules/config";
import { LogClass, maskEmail } from "@/app/modules/logger";
import { Inject, Injectable, Logger } from "@nestjs/common";
import { ConfigService } from "@nestjs/config";

const _RESEND_EMAILS_URL = "https://api.resend.com/emails";
const _REQUEST_TIMEOUT_MS = 10_000;

type TOutgoingEmail = {
	toAddress: string;
	subject: string;
	html: string;
	text: string;
	/** What the dev log line calls this email, e.g. `magic link`. */
	devLogLabel: string;
	/** The link printed by the dev log fallback. */
	devLogUrl: string;
};

/** Escapes user-supplied text (restaurant names, rejection reasons) for HTML bodies. */
function escapeHtml(value: string): string {
	return value
		.replaceAll("&", "&amp;")
		.replaceAll("<", "&lt;")
		.replaceAll(">", "&gt;")
		.replaceAll('"', "&quot;")
		.replaceAll("'", "&#39;");
}

/**
 * Sends transactional email through the Resend HTTP API over plain `fetch`.
 *
 * With no `RESEND_API_KEY` (development only -- config requires it in
 * production) the link is logged instead of sent, so sign-in works locally.
 */
@LogClass()
@Injectable()
export class ResendAdapter {
	private readonly _logger = new Logger(ResendAdapter.name);
	private readonly _apiKey: string | undefined;
	private readonly _from: string;

	constructor(
		@Inject(ConfigService)
		private readonly _configService: ConfigService<TConfig>,
	) {
		this._apiKey = this._configService.get("RESEND_API_KEY");
		this._from = this._configService.getOrThrow("RESEND_FROM_EMAIL");
	}

	/** Whether real delivery is configured. */
	public isConfigured(): boolean {
		return Boolean(this._apiKey);
	}

	/** Emails the sign-in link; throws on a non-2xx Resend response. */
	public async sendMagicLink(
		toAddress: string,
		magicLinkUrl: string,
		expiresInMinutes: number,
	): Promise<void> {
		await this._deliver({
			toAddress,
			subject: "Your Nearplate sign-in link",
			html: this._html(magicLinkUrl, expiresInMinutes),
			text: this._text(magicLinkUrl, expiresInMinutes),
			devLogLabel: "magic link",
			devLogUrl: magicLinkUrl,
		});
	}

	/** Tells an owner their restaurant is live; throws on a non-2xx response. */
	public async sendRestaurantApproved(
		toAddress: string,
		restaurantName: string,
		dashboardUrl: string,
	): Promise<void> {
		const name = escapeHtml(restaurantName);
		await this._deliver({
			toAddress,
			subject: `${restaurantName} is approved on Nearplate`,
			html: `<p>Good news: <strong>${name}</strong> has been approved and is now visible to customers.</p><p><a href="${dashboardUrl}">Open your dashboard</a></p>`,
			text: `Good news: ${restaurantName} has been approved and is now visible to customers.\n\nOpen your dashboard: ${dashboardUrl}`,
			devLogLabel: "approval email",
			devLogUrl: dashboardUrl,
		});
	}

	/** Tells an owner why a restaurant was rejected; throws on a non-2xx response. */
	public async sendRestaurantRejected(
		toAddress: string,
		restaurantName: string,
		reason: string,
		onboardingUrl: string,
	): Promise<void> {
		const name = escapeHtml(restaurantName);
		await this._deliver({
			toAddress,
			subject: `${restaurantName} needs changes before approval`,
			html: `<p>We couldn't approve <strong>${name}</strong> yet.</p><p>Reason: ${escapeHtml(reason)}</p><p><a href="${onboardingUrl}">Fix your details and resubmit</a></p>`,
			text: `We couldn't approve ${restaurantName} yet.\n\nReason: ${reason}\n\nFix your details and resubmit: ${onboardingUrl}`,
			devLogLabel: "rejection email",
			devLogUrl: onboardingUrl,
		});
	}

	/** Sends one email, or logs its link in development when no key is set. */
	private async _deliver(email: TOutgoingEmail): Promise<void> {
		if (!this._apiKey) {
			this._logDevLink(email);
			return;
		}
		const response = await fetch(_RESEND_EMAILS_URL, {
			method: "POST",
			headers: {
				Authorization: `Bearer ${this._apiKey}`,
				"Content-Type": "application/json",
			},
			body: JSON.stringify({
				from: this._from,
				to: [email.toAddress],
				subject: email.subject,
				html: email.html,
				text: email.text,
			}),
			signal: AbortSignal.timeout(_REQUEST_TIMEOUT_MS),
		});
		if (!response.ok) {
			throw new Error(`Resend responded with ${response.status}`);
		}
	}

	/**
	 * Development fallback: prints the link so flows work without email. The
	 * URL goes in its own field because the logger redacts `token=` inside
	 * message strings. Refuses to run in production, where a logged link would
	 * be a leaked credential (config already requires the key there).
	 */
	private _logDevLink(email: TOutgoingEmail): void {
		if (this._configService.get("NODE_ENV") === "production") {
			throw new Error("RESEND_API_KEY is required in production");
		}
		this._logger.warn({
			message: `RESEND_API_KEY not set; ${email.devLogLabel} for ${maskEmail(email.toAddress)}`,
			magicLinkUrl: email.devLogUrl,
		});
	}

	/** HTML body; the URL is generated by us, never user input. */
	private _html(url: string, minutes: number): string {
		return `<p>Click to sign in to Nearplate:</p><p><a href="${url}">Sign in</a></p><p>This link expires in ${minutes} minutes and can be used once. If you didn't ask for it, ignore this email.</p>`;
	}

	/** Plain-text alternative. */
	private _text(url: string, minutes: number): string {
		return `Sign in to Nearplate: ${url}\n\nThis link expires in ${minutes} minutes and can be used once. If you didn't ask for it, ignore this email.`;
	}
}
